### ISSUE TITLE
[BUG] Ledger Nano does not work after the last UI update

### ISSUE THREAD

**Issue by myexec** [Switcheo/zilswap-webapp#53]
After the last UI update I have some problem signing a transaction with ledger nano x using zilpay extension with chrome. I get this error in the javascript console: Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE.

 I tried both nano s and x
reinstalled zil app on ledger, reinstalled the extension both on chrome and firefox
changed usb cables ... nothing works

Here is console log from Firefox:
`Object { name: "TransportStatusError", message: "Ledger device: UNKNOWN_ERROR (0x6801)", stack: "TransportStatusError@https://zilpay.github.io/ledger-bridge/index.js:1:23058/nTransport/this.send@https://zilpay.github.io/ledger-bridge/index.js:1:88576/nasync*cb@https://zilpay.github.io/ledger-bridge/index.js:1:98446/npromise callbackcb@https://zilpay.github.io/ledger-bridge/index.js:1:98481/npromise callbackcb@https://zilpay.github.io/ledger-bridge/index.js:1:98481/npromise callbackcb@https://zilpay.github.io/ledger-bridge/index.js:1:98481/npromise callbackcb@https://zilpay.github.io/ledger-bridge/index.js:1:98481/npromise callbackcb@https://zilpay.github.io/ledger-bridge/index.js:1:98481/npromise callbackcb@https://zilpay.github.io/ledger-bridge/index.js:1:98481/npromise callbackcb@https://zilpay.github.io/ledger-bridge/index.js:1:98481/npromise callbackcb@https://zilpay.github.io/ledger-bridge/index.js:1:98481/npromise callback*signTxn@https://zilpay.github.io/ledger-bridge/index.js:1:98028/ndecorateAppAPIMethod/<@https://zilpay.github.io/ledger-bridge/index.js:1:91180/n_callee$@https://zilpay.github.io/ledger-bridge/index.js:1:151687/ntryCatch@https://zilpay.github.io/ledger-bridge/index.js:1:154579/ninvoke@https://zilpay.github.io/ledger-bridge/index.js:1:154210/ndefineIteratorMethods/</<@https://zilpay.github.io/ledger-bridge/index.js:1:155345/nasyncGeneratorStep@https://zilpay.github.io/ledger-bridge/index.js:1:87027/n_next@https://zilpay.github.io/ledger-bridge/index.js:1:87362/n_asyncToGenerator/</<@https://zilpay.github.io/ledger-bridge/index.js:1:87499/n_asyncToGenerator/<@https://zilpay.github.io/ledger-bridge/index.js:1:87256/nhandler@https://zilpay.github.io/ledger-bridge/index.js:1:152576/n@https://zilpay.github.io/ledger-bridge/index.js:1:152598/n", statusCode: 26625, statusText: "UNKNOWN_ERROR" }`

**Comment by RavenXce** [comment]
Fixed on Firefox. Won't fix on Chrome due as issue is with Chrome & Ledger firmware.
