### ISSUE TITLE
[BUG] Add funds

### ISSUE THREAD

**Issue by alvesptl** [Switcheo/zilswap-webapp#75]
When I try add funds for test I have this error:

Error: 500 {"error":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"message\":\"Too Many Requests\",\"data\":{\"originalError\":{}},\"stack\":\"Error: Too Many Requests\\n at eval (/www/node_modules/web3-provider-engine/subproviders/rpc.js:52:23)\\n at Request.eval [as _callback] (/www/node_modules/web3-provider-engine/subproviders/rpc.js:54:11)\\n at Request.self.callback (/www/node_modules/request/request.js:186:22)\\n at Request.emit (events.js:315:20)\\n at Request.eval (/www/node_modules/request/request.js:1155:10)\\n at Request.emit (events.js:315:20)\\n at IncomingMessage.eval (/www/node_modules/request/request.js:1077:12)\\n at Object.onceWrapper (events.js:421:28)\\n at IncomingMessage.emit (events.js:327:22)\\n at endReadableNT (internal/streams/readable.js:1327:12)\"}}'"}

The steps is:
Step1-
![image](https://user-images.githubusercontent.com/87129851/124920488-456ed000-dfef-11eb-95a2-571728f21bcf.png)

step2-
![image](https://user-images.githubusercontent.com/87129851/124920608-659e8f00-dfef-11eb-954f-104020ee4ec2.png)

step3 with error-
![image](https://user-images.githubusercontent.com/87129851/124921040-e493c780-dfef-11eb-84ce-bca25a314c5b.png)

I also try add fund on Zil Faucet, but don´t is possible. 

![image](https://user-images.githubusercontent.com/87129851/125004989-91069580-e052-11eb-9d58-b39d65425bdf.png)

![image](https://user-images.githubusercontent.com/87129851/125005054-b72c3580-e052-11eb-8ef8-c3b91c53e4bc.png)

Now, I have this message but don´t receive nothing. 
![image](https://user-images.githubusercontent.com/87129851/125056392-17959400-e0a0-11eb-8d52-f320c1de4171.png)

**Comment by RavenXce** [comment]
This has nothing to do with Zilswap.
