### ISSUE TITLE
[BUG] Transfer in Progress...

### ISSUE THREAD

**Issue by Rawandasloth** [Switcheo/zilswap-webapp#76]
My transfer is stuck in Transfer in Progress... for almost an hour now. 

The UI is showing  Estimated Time Left ~25 Minutes even though the ViewBlock is showing Transaction failed.  

The UI should allow users to either force cancel the transaction or allow them to start a new one when the transaction is stuck.

**Comment by Mr94t3z** [comment]
Yeah, it's was 1 days ago. It's still on progress -
![1 day](https://user-images.githubusercontent.com/52822242/125535327-12e4db6b-33f0-44bd-8db8-56a80e32fa1c.png)
