### ISSUE TITLE
[BUG] ZIL balance not detected on Zilswap

### ISSUE THREAD

**Issue by zannoekhamari** [Switcheo/zilswap-webapp#78]
![Screenshot_20210708-213055](https://user-images.githubusercontent.com/77388235/124950120-aacbbc80-e001-11eb-8100-eb58f9407585.png)
![Screenshot_20210708-213253](https://user-images.githubusercontent.com/77388235/124950139-ae5f4380-e001-11eb-999d-5b24dbc43bde.png)
![Screenshot_20210708-213409](https://user-images.githubusercontent.com/77388235/124950147-af907080-e001-11eb-92bb-e8cc394eb713.png)

i already have 5000 zill tokens in zillpay from faucet, but in zillswap -. so i can't do swap

**Comment by kusmadinata82** [comment]
I have same problem

![Uploading Screenshot_2021-07-10-17-55-31-226_com.kiwibrowser.browser.jpg…]()

**Comment by kusmadinata82** [comment]
![Screenshot_2021-07-10-17-55-54-409_com kiwibrowser browser](https://user-images.githubusercontent.com/83883460/125160766-f076b980-e1a8-11eb-82db-00cf5d3b0c10.jpg)
